version: 2.1
job:
  build:
    docker:
    
      - image: circleci/node:12.16.1
    
    working_directory: ~/SCEMarketProj
      
    steps:
      - checkout
      - run: npm install
      - run: npm test
      